### ISSUE TITLE
Problem with selectElement

### ISSUE THREAD

**Issue by kt1755** [antchfx/xmlquery#10]
I'm using this lib, and i think it's got some problem with selectElement function:

1. I think it should return nil or error as second output rather than excecute panic whenever can't find *Node element with specified name.
2. When I execute InnerText() from Root element, I got text from child element rather than text from current element. It's should return text from current element, or return text with specified element name (InnerText(name string) (string, error) (error happen when element not found))

**Comment by zhengchun** [comment]
Hello, @kt1755 ,thanks for your feedback. I need to explain these questions.

`I think it should return nil or error as second output rather than excecute panic whenever can't find *Node element with specified name.`

In most of cases, `SelectElement` function always return nil if they not found any elements, but will throw panic error if your XPath expression is incorrect (this means you should fix your expression). This point you can check-out source code to review. https://github.com/antchfx/xmlquery/blob/master/query.go#L88

`When I execute InnerText() from Root element, I got text from child element rather than text from current element. It's should return text from current element, or return text with specified element name (InnerText(name string) (string, error) (error happen when element not found))`

The `InnerText` function whether should be including or not including the child-nodes, I'm can't a hundred percent answer you. This design is based on .Net XmlDocument class, a [XmlNode.InnerText](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmlnode.innertext?view=netframework-4.7.2) that will output its child nodes.

**Comment by gwillem** [comment]
I got bitten too, because I copied the example code:
```
channel.SelectElement("link").InnerText()
```
Panics if there's no `link` element, so for unvalidated XML the docs should probably suggest:
```
elt := channel.SelectElement("link")
if elt != nil {
  innerText := elt.InnerText()
}
```
