### ISSUE TITLE
Hanging query

### ISSUE THREAD

**Issue by tamerh** [antchfx/xmlquery#17]
Hi,

while playing with test cases i guess i have managed to find a hanging query. It can be reproduced with following query

```
if node := Find(doc, "//book/price>=44.95"); node == nil {
		t.Fatal("//book/price>=44.95 is not found")
}
```

thanks
Tamer

**Comment by zhengchun** [comment]
It is a bug. you can replacing with `//book[price>=44.95]`, until this bug fix.

**Comment by zhengchun** [comment]
Hello,@tamerh, I'm sure a `//book/price>=44.95` is not correct expression for search nodes in XPath, Because this expression return `Boolean` return (true or false), In .Net, It will throw an `Expression must evaluate to a node-set.` error. You need change to `//book[price>=44.95]` or `(//book[price>=44.95])[1]`.

```go
expr, _ := xpath.Compile("//book/price>=30")
v := expr.Evaluate(xmlquery.CreateXPathNavigator(doc))
fmt.Println(v)
```

**Comment by tamerh** [comment]
Oh yes it is not a valid query and if it throws expression error to avoid hanging case it is fine.
